### PR TITLE
slightly optimize depth & stencil usage

### PR DESCRIPTION
**Pull request by toxieainc**
use only a single glReadPixels for LOS
avoid creating a depth/stencil buffer in the New3D mode
wire error handling for CreateFBO(DepthCopy)
handle black FB init for triple buffering

### CODE REVIEW

**Comment by dukeeeey** [comment]
return ((CreateFBODepthCopy(width, height) == OKAY) && (fboStatus == GL_FRAMEBUFFER_COMPLETE)) ? OKAY : FAIL;

The OKAY and FAIL things are really not needed. The return type is a boolean. I know they are used in other parts of the code but I think it's poor design. The defines are flipped from what you might expect.

**Comment by toxieainc** [comment]
Should i rather do a follow up commit that then removes all of the OKAY/FAIL stuff all over the project?

**Comment by dukeeeey** [comment]
> Should i rather do a follow up commit/PR that then removes all of the OKAY/FAIL stuff all over the project?

Yeah if you want to make a pr for this that's fine.

**Comment by toxieainc** [comment]
By now its used through this PR.. (unless i forgot something)

**Pull request merged**
