### PR TITLE
Improve precision for vp computation

### PR DESCRIPTION
**Pull request by toxieainc**
...to fix regression for at least SRally2 and HarleyD

fixes/improves #201

### CODE REVIEW

**Comment by dukeeeey** [comment]
Are these functionally the same?

	float x = 2.0F / (right - left);
	float y = 2.0F / (top - bottom);
	float a = (right + left) / (right - left);
	float b = (top + bottom) / (top - bottom);

	float x = 2.0f / (right - left);
	float y = 2.0f / (top - bottom);
	float a = left*x + 1.0f;
	float b = bottom*y + 1.0f;

Some games use off-axis projection, harley etc

**Comment by toxieainc** [comment]
I personally prefer it like that, so that its clear whats happening. And in theory you can loose precision, depending on the integer value.

And the code is the same, yes. This way you can share more of the same potential error.

**Comment by toxieainc** [comment]
As for putting additional stuff into such PRs: Sorry, i will try to be more careful then.
I have a lot of local changes piled up, so if some are in the same file as my 'actual fix', and these are rather harmless, then i tend to just squeeze them in, too.

**Comment by dukeeeey** [comment]
I've pushed your changes here locally :) Without the changes for the matrix stuff. I'll test the other code soon.

**Pull request closed without merging**
