### PR TITLE
remove 2 dupe function calls, where ProcessLos should actually be rat…

### PR DESCRIPTION
**Pull request by toxieainc**
…her costly

I think both calls are not really intended, but maybe something else was, at some point?

### CODE REVIEW

**Comment by toxieainc** [comment]
Just checked the history, the first one is a leftover from changing the loops around.
The 2nd one i cannot explain why it is there (its like that since the initial commit), but at least it reads the exact same value back, which should be costly i'd assume, unless the driver does some magical caching under the hood.

**Comment by dukeeeey** [comment]
Yeah that extra call probably shouldn't be there. The line of sight stuff is only used by scud if I recall. It works enough to emulate scud correctly but not 100% sure the logic was correct. There is some LOS flag in the polyheader which maybe does something, I'm not sure.  The sky in scud is marked with that flag. But other games set it to But never use the line of sight stuff.

But back to the thing the extra call should be removed. But I don't think it'll have any performance impact. Calling glreadpixels once for the depth is expensive because you create a sync point in the driver. Basically the driver has to flush the pipeline to return your value. But doing it a second time is basically free.

**Comment by toxieainc** [comment]
Okay. So is there anything that should happen if the call fails or succeeds in addition?

**Comment by dukeeeey** [comment]
Currently no. I think the intention was probably to have some other logic in there. I think it's safe to remove.

**Comment by toxieainc** [comment]
Good, ready to go then IMHO.

**Comment by trzy** [comment]
Thanks!

**Pull request merged**
