### PR TITLE
Add automatic detection for Brew-installed SDL2 and SDL2_net

### PR DESCRIPTION
**Pull request by GregoireLD**
I finally took the time to run multiple tests, with or without brew, and finish this PR.

I made this PR as a suggestion regarding [issue 38](https://github.com/trzy/Supermodel/issues/38).
I tried to keep my changes to the minimum, and tried my best to keep current compiling process unchanged.

What this does :
Tests if brew is installed, and if it is, tests if sdl2 and sdl2_net are installed using brew. Only in this very case, the installation will use "brewed" paths to sdl libraries.
In all other cases, the process will perform as before, unchanged.

In addition, I made a "compile from source" brew recipe that also works with these changes (This is the part that made me cancel my previous PR). If it's merged, I will make sure the brew recipe is changed accordingly (current public Brew recipe installs the 0.2a version from eons ago).

As stated before, this is pretty much my first PR, so feel free to deny it, if you think it's bad idea, or doesn't meet the prerequisites, no hard feeling 😊

### CODE REVIEW

**Comment by TheBrinkOfTomorrow** [comment]
Sorry to be a pain, but I'd very much prefer this to *not* be the default option on macOS, as I want to build with the SDL frameworks (same as I always have)....

i.e. I have the SDL frameworks installed, and SDL via brew, and I don't want to have to uninstall SDL via brew every time I want to build Supermodel...

Is there a way you could make using brew SDL and option using the makefile?.. e.g   make -f ./Makefiles/Makefile.OSX BREW_SDL=1

**Comment by trzy** [comment]
Looks like there is some controversy... brewing. :D

(I'll try to get to these PRs this weekend. Thanks for your patience!)

**Comment by GregoireLD** [comment]
Yes it is possible, but it was also brought to my attention it would be best to avoid making new makefile flags, if possible.
Just to be sure to understand the situation you are in, you have both manually installed SDL2 and brew-curated SDL2 on your computer, but you prefer it to use the manually installed occurence, am I understanding correctly ?

**Comment by trzy** [comment]
I think that is what he is saying, yes.

**Comment by TheBrinkOfTomorrow** [comment]
Yes. That’s exactly what I meant.
Sorry for the delay in responding.

**Comment by trzy** [comment]
GregoireLD: Did you want some more time to make that modification? Another thought I had is having two separate Mac OSX Makefiles (including a .Brew one). It does seem nicer to auto-detect, though.

**Comment by jw0z96** [comment]
Just thought I'd drop a comment here, as I recently made similar changes locally in order to build on my machine, using `sdl2` and `sdl2_net` from homebrew.

Using `sdl2-config` could simplify this somewhat - it's provided in the brew install of SDL2, and allows for the same functionality used in the [Makefile.UNIX](https://github.com/trzy/Supermodel/tree/master/Makefiles/Makefile.UNIX). These were the changes I made to the Makefile :

```
SDL_CFLAGS = `sdl2-config --cflags`

SDL_LIBS = `sdl2-config --libs`
SDL_LIBS += -framework AGL -framework OpenGL -framework GLUT -framework Cocoa

ifeq ($(strip $(NET_BOARD)),1)
    SDL_LIBS += -lSDL2_net
endif
```

I'm not sure whether `sdl2-config` is provided with the system-provided SDL2 libraries. If it is, then perhaps this is all that's needed - otherwise, `$(shell which sdl2-config)` might be suitable for detecting whether SDL2 is installed via brew.

Hope this helps!

**Comment by GregoireLD** [comment]
Hi, and sorry for the hiatus, I currently am on holiday in Japan, with less available time as usual.

After reading these advice, I plan to alter my PR as follow, if it suits the project:

- keep one macOS makefile for both brew and non-brew builds
- Use “which” to auto-detect user preferences towards brew or non brew sdl
- expose a completely optional flags (i currently use it internally, but it can be used by the user) to force brew, or non brew builds

let me know how it sounds, and in the meantime I will start coding when I get some rest 😊

**Comment by trzy** [comment]
By the way, I just tried out the Makefiles on my Mac and am getting these errors:

```
--------------------------------------------------------------------------------
Linking Supermodel     : bin/supermodel
--------------------------------------------------------------------------------
ld: warning: option -s is obsolete and being ignored
Undefined symbols for architecture arm64:
  "FileSystemPath::GetPath(FileSystemPath::PathType)", referenced from:
      Screenshot() in Main.o
      Supermodel(Game const&, ROMSet*, IEmulator*, CInputs*, COutputs*) in Main.o
      LoadState(IEmulator*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in Main.o
      __GLOBAL__sub_I_Main.cpp in Main.o
  "_glBindTexture", referenced from:
      Legacy3D::CLegacy3D::DecodeTexture(int, int, int, int, int) in Legacy3D.o
      Legacy3D::CLegacy3D::RenderFrame() in Legacy3D.o
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
      New3D::R3DFrameBuffers::CreateFBO(int, int) in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CreateTexture(int, int) in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::BindTexture(New3D::Layer) in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::Draw() in R3DFrameBuffers.o
      ...
  "_glBlendFunc", referenced from:
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
      New3D::R3DFrameBuffers::Draw() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CompositeAlphaLayer() in R3DFrameBuffers.o
      New3D::R3DScrollFog::DrawScrollFog(float*, float, float, float*, float*) in R3DScrollFog.o
      CRender2D::Setup2D(bool) in Render2D.o
  "_glClear", referenced from:
      Legacy3D::CLegacy3D::RenderFrame() in Legacy3D.o
      New3D::CNew3D::RenderFrame() in New3D.o
      CRender2D::Setup2D(bool) in Render2D.o
      SetGLGeometry(unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, bool) in Main.o
  "_glClearColor", referenced from:
      CRender2D::Setup2D(bool) in Render2D.o
      SetGLGeometry(unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, bool) in Main.o
  "_glClearDepth", referenced from:
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
      SetGLGeometry(unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, bool) in Main.o
  "_glColorPointer", referenced from:
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
  "_glCullFace", referenced from:
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
  "_glDeleteTextures", referenced from:
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
      Legacy3D::CLegacy3D::~CLegacy3D() in Legacy3D.o
      New3D::R3DFrameBuffers::DestroyFBO() in R3DFrameBuffers.o
      New3D::CNew3D::~CNew3D() in New3D.o
      CRender2D::~CRender2D() in Render2D.o
  "_glDepthFunc", referenced from:
      Legacy3D::CLegacy3D::RenderFrame() in Legacy3D.o
      New3D::CNew3D::SetRenderStates() in New3D.o
      New3D::CNew3D::RenderFrame() in New3D.o
      SetGLGeometry(unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, bool) in Main.o
  "_glDepthMask", referenced from:
      New3D::CNew3D::SetRenderStates() in New3D.o
      New3D::R3DScrollFog::DrawScrollFog(float*, float, float, float*, float*) in R3DScrollFog.o
  "_glDisable", referenced from:
      Legacy3D::CLegacy3D::RenderFrame() in Legacy3D.o
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
      New3D::R3DFrameBuffers::Draw() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CompositeBaseLayer() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CompositeAlphaLayer() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::DrawOverTransLayers() in R3DFrameBuffers.o
      New3D::CNew3D::SetRenderStates() in New3D.o
      ...
  "_glDisableClientState", referenced from:
      Legacy3D::CLegacy3D::RenderFrame() in Legacy3D.o
  "_glDrawArrays", referenced from:
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
      New3D::R3DFrameBuffers::Draw() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::DrawBaseLayer() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::DrawAlphaLayer() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CompositeBaseLayer() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CompositeAlphaLayer() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::DrawOverTransLayers() in R3DFrameBuffers.o
      ...
  "_glDrawBuffer", referenced from:
      New3D::R3DFrameBuffers::SetFBO(New3D::Layer) in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::Draw() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CompositeBaseLayer() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CompositeAlphaLayer() in R3DFrameBuffers.o
  "_glEnable", referenced from:
      Legacy3D::CLegacy3D::RenderFrame() in Legacy3D.o
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
      New3D::R3DFrameBuffers::Draw() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CompositeAlphaLayer() in R3DFrameBuffers.o
      New3D::CNew3D::SetRenderStates() in New3D.o
      New3D::R3DShader::SetMeshUniforms(New3D::Mesh const*) in R3DShader.o
      ...
  "_glEnableClientState", referenced from:
      Legacy3D::CLegacy3D::RenderFrame() in Legacy3D.o
  "_glFogf", referenced from:
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
  "_glFogfv", referenced from:
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
  "_glFrontFace", referenced from:
      Legacy3D::CLegacy3D::RenderFrame() in Legacy3D.o
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
  "_glGenTextures", referenced from:
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
      New3D::R3DFrameBuffers::CreateFBO(int, int) in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CreateTexture(int, int) in R3DFrameBuffers.o
      New3D::CNew3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in New3D.o
      CRender2D::CRender2D(Util::Config::Node const&) in Render2D.o
  "_glGetError", referenced from:
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
      Legacy3D::CLegacy3D::CreateModelCache(Legacy3D::ModelCache*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, bool) in Models.o
  "_glGetFloatv", referenced from:
      Legacy3D::CLegacy3D::AppendDisplayList(Legacy3D::ModelCache*, bool, Legacy3D::VBORef const*) in Models.o
  "_glGetIntegerv", referenced from:
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
      PrintGLInfo(bool, bool, bool) in Main.o
      CreateGLScreen(bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, bool, bool) in Main.o
  "_glGetString", referenced from:
      PrintGLInfo(bool, bool, bool) in Main.o
      CreateGLScreen(bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, bool, bool) in Main.o
  "_glGetTexLevelParameteriv", referenced from:
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
  "_glLoadIdentity", referenced from:
      Legacy3D::CLegacy3D::InitMatrixStack(unsigned int) in Legacy3D.o
      Legacy3D::CLegacy3D::RenderViewport(unsigned int, int, bool) in Legacy3D.o
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
  "_glLoadMatrixf", referenced from:
      Legacy3D::CLegacy3D::InitMatrixStack(unsigned int) in Legacy3D.o
  "_glMatrixMode", referenced from:
      Legacy3D::CLegacy3D::RenderViewport(unsigned int, int, bool) in Legacy3D.o
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
  "_glMultMatrixf", referenced from:
      Legacy3D::CLegacy3D::MultMatrix(unsigned int) in Legacy3D.o
      Legacy3D::CLegacy3D::InitMatrixStack(unsigned int) in Legacy3D.o
      Legacy3D::CLegacy3D::DescendCullingNode(unsigned int) in Legacy3D.o
  "_glNormalPointer", referenced from:
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
  "_glPixelStorei", referenced from:
      Legacy3D::CLegacy3D::DecodeTexture(int, int, int, int, int) in Legacy3D.o
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
      New3D::CNew3D::UploadTextures(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in New3D.o
  "_glPopMatrix", referenced from:
      Legacy3D::CLegacy3D::DescendCullingNode(unsigned int) in Legacy3D.o
  "_glPushMatrix", referenced from:
      Legacy3D::CLegacy3D::DescendCullingNode(unsigned int) in Legacy3D.o
  "_glReadPixels", referenced from:
      New3D::CNew3D::ProcessLos(int) in New3D.o
      Screenshot() in Main.o
  "_glScalef", referenced from:
      Legacy3D::CLegacy3D::InitMatrixStack(unsigned int) in Legacy3D.o
  "_glScissor", referenced from:
      SetGLGeometry(unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*, bool) in Main.o
  "_glStencilFunc", referenced from:
      Legacy3D::CLegacy3D::RenderFrame() in Legacy3D.o
      New3D::CNew3D::SetRenderStates() in New3D.o
  "_glStencilMask", referenced from:
      Legacy3D::CLegacy3D::RenderFrame() in Legacy3D.o
      New3D::CNew3D::SetRenderStates() in New3D.o
  "_glStencilOp", referenced from:
      Legacy3D::CLegacy3D::RenderFrame() in Legacy3D.o
      New3D::CNew3D::SetRenderStates() in New3D.o
  "_glTexCoordPointer", referenced from:
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
  "_glTexImage2D", referenced from:
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
      New3D::R3DFrameBuffers::CreateFBO(int, int) in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CreateTexture(int, int) in R3DFrameBuffers.o
      New3D::CNew3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in New3D.o
      CRender2D::CRender2D(Util::Config::Node const&) in Render2D.o
  "_glTexParameteri", referenced from:
      Legacy3D::CLegacy3D::RenderFrame() in Legacy3D.o
      Legacy3D::CLegacy3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in Legacy3D.o
      New3D::R3DFrameBuffers::CreateFBO(int, int) in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CreateTexture(int, int) in R3DFrameBuffers.o
      New3D::CNew3D::Init(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in New3D.o
      CRender2D::CRender2D(Util::Config::Node const&) in Render2D.o
  "_glTexSubImage2D", referenced from:
      Legacy3D::CLegacy3D::DecodeTexture(int, int, int, int, int) in Legacy3D.o
      New3D::CNew3D::UploadTextures(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) in New3D.o
      CRender2D::PreRenderFrame() in Render2D.o
  "_glTranslatef", referenced from:
      Legacy3D::CLegacy3D::DescendCullingNode(unsigned int) in Legacy3D.o
  "_glVertexPointer", referenced from:
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
  "_glViewport", referenced from:
      Legacy3D::CLegacy3D::DrawDisplayList(Legacy3D::ModelCache*, Legacy3D::POLY_STATE) in Models.o
      New3D::R3DFrameBuffers::Draw() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CompositeBaseLayer() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::CompositeAlphaLayer() in R3DFrameBuffers.o
      New3D::R3DFrameBuffers::DrawOverTransLayers() in R3DFrameBuffers.o
      New3D::CNew3D::DrawScrollFog() in New3D.o
      New3D::CNew3D::RenderScene(int, bool, New3D::Layer) in New3D.o
      ...
  "_gluPerspective", referenced from:
      Legacy3D::CLegacy3D::RenderViewport(unsigned int, int, bool) in Legacy3D.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/supermodel] Error 1
```

**Comment by trzy** [comment]
Closed due to no resolution.

**Pull request closed without merging**
