### PR TITLE
change all INT16 mixing/intermediate clamping to floats

### PR DESCRIPTION
**Pull request by toxieainc**
also fixes 3 bugs:
1) mpeg right channel volume attenuation was always using the left channel volume instead
2) too high MusicVolume setting was not clamped to 0..200
3) too high SoundVolume setting was not clamped to 0..200

partially addresses issue #22

### CODE REVIEW

**Comment by trzy** [comment]
Question: doesn't float reduce precision? As I recall, mixing was currently being done with fixed point arithmetic. I think I was using 24.8.

**Comment by toxieainc** [comment]
In principle this would be true. If one would always keep the 24.8 data around and would never go to 16bits inbetween (but if you look at the code, there are multiple stages, each time one has 16bit data at the end). Also all the ops always do truncation, also when doing the volume attenuation precomputations, etc. So this way one also introduces an implicit systematic error.
Obviously this is all not earth shattering, but as the float only code should even be faster nowadays, i think getting these 1-2 bits/sample improvement and no systematic error is better.  ;)
To do everything 'correctly' one would also need to add some dithering on the final float->INT16 step, but i think this is not really worth it for our use case.

**Comment by toxieainc** [comment]
Oh, and i forgot to mention: If the 18bit DAC path is ever triggered by some games (didn't check), then my change will also keep that data unclamped until the final stage.
Although i also must admit that i don't really understand where these additional 2bits are compensated for. If a game would trigger the same volume range as another one in the 16bit DAC path, then the 18bit one will always be 4x the scale in the end when mixing. Before, it was just clamped (=bad), but now it could just be the full 18bits.
Do you have a clue how this is supposed to be handled? And which games trigger the 18bit DAC path?

**Comment by toxieainc** [comment]
Addon: Seems like at least the majority of all the games triggers the 18bit DAC path.
So this means that ALL these were potentially cut off/clamped on loud sounds! So the 2nd PR will then definetly fix this. This will change the loudness though of everything coming out of SCSP, but its the correct thing to do!

**Comment by trzy** [comment]
There's an 18-bit DAC on the SCSP? That's interesting and a great catch! This PR looks good! Thanks!

**Comment by toxieainc** [comment]
Thanks! As for the 18 bit DAC: Just did some tests on all kind of games, and seems that even when waving the 18bit data through (which in theory could be 4x the value range), then only Daytona triggers some clamping, and only for a handful of samples now and then.

**Comment by dukeeeey** [comment]
I haven't really looked at the audio code much .. But 18bit DAC? I didn't even know this was a thing. Why does it exist? :)

**Comment by toxieainc** [comment]
No clue for the specific case here. But at least it seems like the board can work at >=18bit fidelity. And then there are 2 DAC types, a 18bit and a 16bit one. The 16bit one obviously will slash this additional fidelity, while the 18bit one keeps it when going to analogue output(s).
But as mentioned above, seems like fortunately it doesn't really matter for SuperModel, as only Daytona2 actually (rarely) seems to trigger it.
Otherwise, i haven't checked what happens if one would change the volume in the menu of other games (at least for Daytona2 its already at max by default).

**Comment by trzy** [comment]
> I haven't really looked at the audio code much .. But 18bit DAC? I didn't even know this was a thing. Why does it exist? :)

How else do you expect to "feel the heartbeat of my machine, through this tight seat" if not with 18-bit fidelity??

**Pull request merged**
