### PR TITLE
Implement different upscaling filters for the 2D layers

### PR DESCRIPTION
**Pull request by toxieainc**
none, biquintic, bilinear (=old one), bicubic

All have their pros and cons, i personally favor either complete pixel sharpness (=none) or completely blurring away pixel borders (=bicubic), depending on the game

### CODE REVIEW

**Comment by dukeeeey** [comment]
Should bilinear be default? Honestly I've never even heard of biquintic. I know that bicubic can offer slightly better image quality but requires more texture reads so is slightly more expensive.

**Comment by toxieainc** [comment]
Biquintic is based on a simple idea, popularized by iq: https://iquilezles.org/articles/texture/
It features smoother pixel 'borders', but looks overall a bit sharper than bilinear. I think it fits a bit better than bilinear. Will make some comparison shots.

**Comment by toxieainc** [comment]
nearest
biquintic
bilinear
bicubic

**Comment by toxieainc** [comment]
So, as you can see, the filters are basically increasing in 'perceived bluriness'.

**Comment by dukeeeey** [comment]
On my phone the shader toy demo works at 1.3 fps lol
I'd say use the fast and dumb (bilinear) as default and if people want to experiment with others they can.

**Comment by toxieainc** [comment]
In practice it should be almost for free compared to bilinear (its just a bunch of simple math ops), but i'll change it.

**Pull request merged**
