### PR TITLE
small optimizations and small precision improvements to the quad and …

### PR DESCRIPTION
**Pull request by toxieainc**
…tri shaders

rather harmless and also IMHO does not harm readability, etc, maybe even rather the contrary

### CODE REVIEW

**Comment by trzy** [comment]
Will try to look at this and the other PR this weekend!

**Review by trzy — COMMENTED** [review]
Quite a lot of changes here. Some I can understand but others I am not sure of. Has Ian confirmed that this doesn't break anything?

**Comment by dukeeeey** [comment]
> 

I haven't tried the code but it looks fine. Personally I'd leave the code the same for LinearTexLocations in the quad shader. The micro optimisations at least for me obfuscate the meaning of what the code is doing

**Comment by trzy** [comment]
toxieainc: possible to make Ian's suggested fix so we can merge this in?

**Comment by toxieainc** [comment]
Yup, will do.

**Comment by toxieainc** [comment]
I reverted everything in LinearTexLocations as requested

**Comment by toxieainc** [comment]
Will check what is leftover from this commit after @dukeeeey did the GL revamp

**Pull request closed without merging**
