### PR TITLE
More static analysis fixes

### PR DESCRIPTION
**Pull request by toxieainc**
and one more in the hope of fixing #178 or #203, unfortunately no luck with those

### CODE REVIEW

**Comment by dukeeeey** [comment]
const unsigned* const __restrict 

That's not standard c++.

**Comment by toxieainc** [comment]
True, but pretty much all common c++ compilers accept it, we also use it in all commercial code i work on for a living (which covers pretty much all x86/arm/ppc platforms in use nowadays). In fact, most c++ compilers generate less efficient code without it.
But if you prefer, i can also remove it, of course.

**Comment by dukeeeey** [comment]
Supermodel ends up on all kinds of platforms you wouldn't expect, xbox etc. Would prefer to use standard functions. But the texture loading code is not a hot path. In such cases readability is more preferable.

**Comment by toxieainc** [comment]
Removed again..

**Pull request merged**
